In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
uploaded = files.upload()

Saving bank.csv to bank.csv

In [4]:
df = pd.read_csv('bank.csv')

In [5]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [9]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,1528.538524,15.658036,371.993818,2.508421,51.330407,0.832557
std,11.913369,3225.413326,8.420740,347.128386,2.722077,108.758282,2.292007
min,18.000000,-6847.000000,1.000000,2.000000,1.000000,-1.000000,0.000000
25%,32.000000,122.000000,8.000000,138.000000,1.000000,-1.000000,0.000000
50%,39.000000,550.000000,15.000000,255.000000,2.000000,-1.000000,0.000000
75%,49.000000,1708.000000,22.000000,496.000000,3.000000,20.750000,1.000000
max,95.000000,81204.000000,31.000000,3881.000000,63.000000,854.000000,58.000000

In [7]:
df.shape

(11162, 17)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB

In [10]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [14]:
X = df.drop('deposit', axis=1)
y = df['deposit']

In [15]:
categorical_cols = X.select_dtypes(include=['object']).columns
numerical_cols = X.select_dtypes(include=np.number).columns

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_encoded_categorical = pd.DataFrame(encoder.fit_transform(X[categorical_cols]))

X_encoded_categorical.columns = encoder.get_feature_names_out(categorical_cols)

X_encoded_categorical.index = X.index

X_processed = pd.concat([X[numerical_cols], X_encoded_categorical], axis=1)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.3, random_state=42)

print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")

Training features shape: (7813, 51)
Testing features shape: (3349, 51)
Training target shape: (7813,)
Testing target shape: (3349,)

In [21]:
cart_dt_model = DecisionTreeClassifier(random_state=42)

cart_dt_model.fit(X_train, y_train)

print("CART Decision Tree model trained successfully!")

CART Decision Tree model trained successfully!

In [22]:
y_pred_cart = cart_dt_model.predict(X_test)

accuracy_cart = accuracy_score(y_test, y_pred_cart)
report_cart = classification_report(y_test, y_pred_cart)
conf_matrix_cart = confusion_matrix(y_test, y_pred_cart)

print(f"Accuracy of CART Decision Tree: {accuracy_cart:.4f}")
print("\nClassification Report (CART Decision Tree):\n")
print(report_cart)
print("\nConfusion Matrix (CART Decision Tree):\n")
print(conf_matrix_cart)

Accuracy of CART Decision Tree: 0.7850

Classification Report (CART Decision Tree):

              precision    recall  f1-score   support

          no       0.79      0.80      0.79      1742
         yes       0.78      0.77      0.77      1607

    accuracy                           0.79      3349
   macro avg       0.78      0.78      0.78      3349
weighted avg       0.78      0.79      0.78      3349


Confusion Matrix (CART Decision Tree):

[[1395  347]
 [ 373 1234]]

In [29]:
id3_c45_dt_model = DecisionTreeClassifier(criterion='entropy', random_state=42)

id3_c45_dt_model.fit(X_train, y_train)

print("ID3/C4.5 Decision Tree model (Information Gain) trained successfully!")

ID3/C4.5 Decision Tree model (Information Gain) trained successfully!

In [30]:
y_pred_id3_c45 = id3_c45_dt_model.predict(X_test)

accuracy_id3_c45 = accuracy_score(y_test, y_pred_id3_c45)
report_id3_c45 = classification_report(y_test, y_pred_id3_c45)
conf_matrix_id3_c45 = confusion_matrix(y_test, y_pred_id3_c45)

print(f"Accuracy of ID3/C4.5 Decision Tree: {accuracy_id3_c45:.4f}")
print("\nClassification Report (ID3/C4.5 Decision Tree):\n")
print(report_id3_c45)
print("\nConfusion Matrix (ID3/C4.5 Decision Tree):\n")
print(conf_matrix_id3_c45)

Accuracy of ID3/C4.5 Decision Tree: 0.7919

Classification Report (ID3/C4.5 Decision Tree):

              precision    recall  f1-score   support

          no       0.80      0.80      0.80      1742
         yes       0.78      0.79      0.78      1607

    accuracy                           0.79      3349
   macro avg       0.79      0.79      0.79      3349
weighted avg       0.79      0.79      0.79      3349


Confusion Matrix (ID3/C4.5 Decision Tree):

[[1390  352]
 [ 345 1262]]

In [31]:
print(f"CART (Gini Impurity) Model Accuracy: {accuracy_cart:.4f}")
print(f"ID3/C4.5 (Information Gain) Model Accuracy: {accuracy_id3_c45:.4f}")

print("\n--- CART (Gini) Classification Report ---")
print(report_cart)

print("\n--- ID3/C4.5 (Entropy) Classification Report ---")
print(report_id3_c45)

CART (Gini Impurity) Model Accuracy: 0.7850
ID3/C4.5 (Information Gain) Model Accuracy: 0.7919

--- CART (Gini) Classification Report ---
              precision    recall  f1-score   support

          no       0.79      0.80      0.79      1742
         yes       0.78      0.77      0.77      1607

    accuracy                           0.79      3349
   macro avg       0.78      0.78      0.78      3349
weighted avg       0.78      0.79      0.78      3349


--- ID3/C4.5 (Entropy) Classification Report ---
              precision    recall  f1-score   support

          no       0.80      0.80      0.80      1742
         yes       0.78      0.79      0.78      1607

    accuracy                           0.79      3349
   macro avg       0.79      0.79      0.79      3349
weighted avg       0.79      0.79      0.79      3349