In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/insurance_data.csv")

In [ ]:
df.head()

   age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               27 non-null     int64
 1   bought_insurance  27 non-null     int64
dtypes: int64(2)
memory usage: 564.0 bytes

In [ ]:
print('Null values in the dataset:')
print(df.isnull().sum())

Null values in the dataset:
age                 0
bought_insurance    0
dtype: int64

In [ ]:
X = df[['age']]
Y = df['bought_insurance']

print('X (Features - age head):')
display(X.head())
print('\nY (Target - bought_insurance head):')
display(Y.head())

X (Features - age head):

   age
0   22
1   25
2   47
3   52
4   46

Y (Target - bought_insurance head):

0    0
1    0
2    1
3    0
4    1
Name: bought_insurance, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print(f'Shape of X_train: {X_train.shape}')
print(f'Shape of X_test: {X_test.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_test: {y_test.shape}')

Shape of X_train: (21, 1)
Shape of X_test: (6, 1)
Shape of y_train: (21,)
Shape of y_test: (6,)

In [ ]:
model = linear_model.LogisticRegression()
model.fit(X_train, y_train)
print('Model training complete.')

Model training complete.

In [ ]:
accuracy = model.score(X_test, y_test)
print(f'Accuracy of the Logistic Regression model: {accuracy:.4f}')

Accuracy of the Logistic Regression model: 1.0000